# Generated by Django 2.2.17 on 2021-03-05 15:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authnapp', '0003_auto_20210305_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 7, 15, 55, 13, 803008, tzinfo=utc), verbose_name='актуальность ключа'),
        ),
    ]
