# Generated by Django 2.2.17 on 2021-03-18 09:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authnapp', '0004_auto_20210317_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 20, 9, 26, 52, 534309, tzinfo=utc), verbose_name='актуальность ключа'),
        ),
    ]
