# Generated by Django 2.2.17 on 2021-03-20 12:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authnapp', '0005_auto_20210318_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 22, 12, 52, 45, 769433, tzinfo=utc), verbose_name='актуальность ключа'),
        ),
    ]
