# Generated by Django 2.2.17 on 2021-03-18 18:43

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("authnapp", "0006_auto_20210315_1744"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shopuser",
            name="activation_key_expires",
            field=models.DateTimeField(
                default=datetime.datetime(2021, 3, 20, 18, 43, 42, 746529, tzinfo=utc),
                verbose_name="актуальность ключа",
            ),
        ),
    ]
