# Generated by Django 2.2.17 on 2021-03-14 12:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authnapp', '0006_auto_20210314_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 16, 12, 27, 56, 448120, tzinfo=utc), verbose_name='актуальность ключа'),
        ),
    ]
