# Generated by Django 2.2.17 on 2021-03-10 15:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authnapp', '0006_auto_20210310_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 12, 15, 56, 27, 907384, tzinfo=utc), verbose_name='актуальность ключа'),
        ),
    ]
