# Generated by Django 2.2.17 on 2021-03-29 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authnapp', '0007_auto_20210318_1843'),
        ('authnapp', '0003_auto_20210305_1431'),
    ]

    operations = [
    ]
