# Generated by Django 2.2.17 on 2021-03-21 11:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authnapp', '0012_auto_20210320_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 23, 11, 48, 38, 605615, tzinfo=utc), verbose_name='актуальность ключа'),
        ),
    ]
